# Generated by Django 4.2.7 on 2026-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="stripe_price_id",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="stripe_product_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="metadata",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="stripe_customer_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="stripe_payment_intent_id",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="stripe_subscription_id",
        ),
        migrations.RemoveField(
            model_name="usersubscription",
            name="stripe_subscription_id",
        ),
    ]
