# Generated by Django 4.2.7 on 2026-05-27 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMEProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                (
                    "registration_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("industry", models.CharField(default="Technology", max_length=100)),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Lesotho", "Lesotho"),
                            ("South Africa", "South Africa"),
                        ],
                        default="Lesotho",
                        max_length=100,
                    ),
                ),
                (
                    "lesotho_district",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Maseru", "Maseru"),
                            ("Leribe", "Leribe"),
                            ("Mafeteng", "Mafeteng"),
                            ("Mohales Hoek", "Mohale's Hoek"),
                            ("Quthing", "Quthing"),
                            ("Qachas Nek", "Qacha's Nek"),
                            ("Mokhotlong", "Mokhotlong"),
                            ("Thaba-Tseka", "Thaba-Tseka"),
                            ("Butha-Buthe", "Butha-Buthe"),
                            ("Berea", "Berea"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "sa_province",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Gauteng", "Gauteng"),
                            ("Western Cape", "Western Cape"),
                            ("KwaZulu-Natal", "KwaZulu-Natal"),
                            ("Eastern Cape", "Eastern Cape"),
                            ("Free State", "Free State"),
                            ("Mpumalanga", "Mpumalanga"),
                            ("Limpopo", "Limpopo"),
                            ("North West", "North West"),
                            ("Northern Cape", "Northern Cape"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("sa_city", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(default="Business description coming soon..."),
                ),
                ("founded_year", models.IntegerField(default=2024)),
                ("employee_count", models.CharField(default="1-10", max_length=50)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("LSL", "Lesotho Loti (M)"),
                            ("ZAR", "South African Rand (R)"),
                        ],
                        default="LSL",
                        max_length=3,
                    ),
                ),
                (
                    "funding_needed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "funding_purpose",
                    models.TextField(default="Business growth and expansion"),
                ),
                (
                    "annual_revenue",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "profit_margin",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("readiness_score", models.IntegerField(default=0)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sme_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sme_profiles",
            },
        ),
        migrations.CreateModel(
            name="SMEDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("registration", "Business Registration"),
                            ("financial", "Financial Statement"),
                            ("tax", "Tax Clearance"),
                            ("pitch", "Pitch Deck"),
                            ("business_plan", "Business Plan"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file_url", models.URLField()),
                ("file_size", models.IntegerField()),
                ("file_type", models.CharField(max_length=50)),
                ("is_verified", models.BooleanField(default=False)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="sme.smeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "sme_documents",
            },
        ),
        migrations.CreateModel(
            name="SMEActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="sme.smeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "sme_activity_logs",
            },
        ),
        migrations.AddIndex(
            model_name="smeprofile",
            index=models.Index(
                fields=["business_name"], name="sme_profile_busines_b69e99_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smeprofile",
            index=models.Index(
                fields=["country"], name="sme_profile_country_8dbe31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smeprofile",
            index=models.Index(
                fields=["lesotho_district"], name="sme_profile_lesotho_072b45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smeprofile",
            index=models.Index(
                fields=["sa_province"], name="sme_profile_sa_prov_bc6117_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smeprofile",
            index=models.Index(
                fields=["funding_needed"], name="sme_profile_funding_948064_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smeprofile",
            index=models.Index(
                fields=["readiness_score"], name="sme_profile_readine_f568b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smedocument",
            index=models.Index(
                fields=["sme", "document_type"], name="sme_documen_sme_id_efd76c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smedocument",
            index=models.Index(
                fields=["uploaded_at"], name="sme_documen_uploade_a2affc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smeactivitylog",
            index=models.Index(
                fields=["sme", "created_at"], name="sme_activit_sme_id_7fe2ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="smeactivitylog",
            index=models.Index(fields=["action"], name="sme_activit_action_bdb4bc_idx"),
        ),
    ]
