# Generated by Django 4.2.7 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="useractivity",
            name="user_activi_user_id_46cf8f_idx",
        ),
        migrations.RemoveIndex(
            model_name="useractivity",
            name="user_activi_created_9fa3ca_idx",
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="action",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
