# Generated by Django 4.2.7 on 2026-08-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="user",
            name="users_email_4b85f2_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_role_0ace22_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_is_acti_847b48_idx",
        ),
        migrations.RemoveIndex(
            model_name="user",
            name="users_is_veri_63cd6e_idx",
        ),
        migrations.RemoveField(
            model_name="user",
            name="email_verification_sent_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="reset_token_sent_at",
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_user_agent",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
