# Generated by Django 4.2.7 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("training", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprogress",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
