# Generated by Django 4.2.7 on 2026-06-30 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("investor", "0001_initial"),
        ("sme", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("match_score", models.DecimalField(decimal_places=2, max_digits=5)),
                ("match_reasoning", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("connected", "Connected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("messages_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="investor.investorprofile",
                    ),
                ),
                (
                    "sme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="sme.smeprofile",
                    ),
                ),
            ],
            options={
                "db_table": "matches",
            },
        ),
        migrations.CreateModel(
            name="MatchingQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("entity_type", models.CharField(max_length=20)),
                ("entity_id", models.UUIDField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "matching_queue",
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="matching_qu_status_068e9f_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="matching_qu_entity__645c21_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MatchMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="matching.match",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "match_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["match", "created_at"],
                        name="match_messa_match_i_7bb204_idx",
                    ),
                    models.Index(
                        fields=["sender", "is_read"],
                        name="match_messa_sender__6dd14e_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["sme", "status"], name="matches_sme_id_57a38f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["investor", "status"], name="matches_investo_6f27ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["match_score"], name="matches_match_s_4fed38_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="match",
            index=models.Index(
                fields=["created_at"], name="matches_created_c34371_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="match",
            unique_together={("sme", "investor")},
        ),
    ]
