# Generated by Django 4.2.7 on 2026-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("matching", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="matchpreference",
            name="funding_weight",
        ),
        migrations.RemoveField(
            model_name="matchpreference",
            name="impact_weight",
        ),
        migrations.RemoveField(
            model_name="matchpreference",
            name="industry_weight",
        ),
        migrations.RemoveField(
            model_name="matchpreference",
            name="interest_weight",
        ),
        migrations.RemoveField(
            model_name="matchpreference",
            name="location_weight",
        ),
        migrations.RemoveField(
            model_name="matchpreference",
            name="readiness_weight",
        ),
    ]
