# Generated by Django 4.2.7 on 2026-08-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("company_name", models.CharField(blank=True, max_length=255)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("investment_interests", models.JSONField(default=list)),
                ("preferred_industries", models.JSONField(default=list)),
                (
                    "funding_range_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "funding_range_max",
                    models.DecimalField(
                        decimal_places=2, default=1000000, max_digits=15
                    ),
                ),
                (
                    "portfolio_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "verification_status",
                    models.CharField(default="pending", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investor_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestorActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("profile_update", "Profile Updated"),
                            ("investment_made", "Investment Made"),
                            ("match_view", "Match Viewed"),
                            ("match_connect", "Match Connected"),
                            ("portfolio_view", "Portfolio Viewed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investor_activity_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "equity",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("roi", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "investor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investments_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "investments",
                "ordering": ["-date"],
            },
        ),
    ]
