# Generated by Django 4.2.7 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("investor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("declined", "Declined"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
