# Generated by Django 4.2.7 on 2026-06-30 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("users", "User Count"),
                            ("smes", "SME Count"),
                            ("investors", "Investor Count"),
                            ("matches", "Match Count"),
                            ("investments", "Investment Amount"),
                            ("courses", "Course Enrollments"),
                            ("revenue", "Platform Revenue"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("date", models.DateField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "platform_metrics",
                "indexes": [
                    models.Index(
                        fields=["metric_type", "date"],
                        name="platform_me_metric__117479_idx",
                    ),
                    models.Index(fields=["date"], name="platform_me_date_5e991f_idx"),
                ],
                "unique_together": {("metric_type", "date")},
            },
        ),
        migrations.CreateModel(
            name="ImpactMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("economic", "Economic Impact"),
                            ("social", "Social Impact"),
                            ("environmental", "Environmental Impact"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("unit", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("source", models.CharField(blank=True, max_length=200)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "impact_metrics",
                "indexes": [
                    models.Index(
                        fields=["category", "date"],
                        name="impact_metr_categor_e47d3e_idx",
                    ),
                    models.Index(
                        fields=["name", "date"], name="impact_metr_name_de84e0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("profile_view", "Profile View"),
                            ("match_view", "Match View"),
                            ("message_sent", "Message Sent"),
                            ("course_started", "Course Started"),
                            ("course_completed", "Course Completed"),
                            ("investment_made", "Investment Made"),
                            ("document_uploaded", "Document Uploaded"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activities",
                "indexes": [
                    models.Index(
                        fields=["user", "activity_type"],
                        name="user_activi_user_id_290628_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="user_activi_created_9fa3ca_idx"
                    ),
                    models.Index(
                        fields=["activity_type", "created_at"],
                        name="user_activi_activit_1c12f9_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily Report"),
                            ("weekly", "Weekly Report"),
                            ("monthly", "Monthly Report"),
                            ("quarterly", "Quarterly Report"),
                            ("annual", "Annual Report"),
                            ("custom", "Custom Report"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField()),
                ("file_url", models.URLField(blank=True, null=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reports",
                "indexes": [
                    models.Index(
                        fields=["report_type", "generated_at"],
                        name="reports_report__bb4969_idx",
                    ),
                    models.Index(
                        fields=["period_start", "period_end"],
                        name="reports_period__7f1873_idx",
                    ),
                ],
            },
        ),
    ]
