# Generated by Django 4.2.7 on 2026-08-26 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMEProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("business_name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("founded_year", models.IntegerField(blank=True, null=True)),
                ("employee_count", models.CharField(blank=True, max_length=50)),
                (
                    "funding_needed",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("funding_purpose", models.TextField(blank=True)),
                ("financials", models.JSONField(blank=True, default=dict)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("readiness_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sme_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sme_profiles",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SMEOnboarding",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "step",
                    models.CharField(
                        choices=[
                            ("profile", "Profile"),
                            ("business", "Business Info"),
                            ("documents", "Documents"),
                            ("training", "Training"),
                            ("complete", "Complete"),
                        ],
                        default="profile",
                        max_length=20,
                    ),
                ),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sme",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sme_onboarding",
            },
        ),
        migrations.CreateModel(
            name="SMEDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=50)),
                ("file", models.FileField(upload_to="sme/documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sme_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_sme_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sme_documents",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="SMEActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("profile_update", "Profile Updated"),
                            ("document_upload", "Document Uploaded"),
                            ("document_delete", "Document Deleted"),
                            ("onboarding_step", "Onboarding Step"),
                            ("match_view", "Match Viewed"),
                            ("match_connect", "Match Connected"),
                            ("course_enroll", "Course Enrolled"),
                            ("course_complete", "Course Completed"),
                            ("funding_request", "Funding Requested"),
                        ],
                        max_length=50,
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sme_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sme_activity_logs",
                "ordering": ["-created_at"],
            },
        ),
    ]
