# Generated by Django 4.2.7 on 2026-08-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sme", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smedocument",
            name="uploaded_by",
        ),
        migrations.AlterField(
            model_name="smeprofile",
            name="verification_status",
            field=models.CharField(default="pending", max_length=20),
        ),
    ]
