# Generated by Django 4.2.7 on 2026-05-27 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceResource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("equipment", "Equipment"),
                            ("materials", "Materials"),
                            ("services", "Services"),
                            ("export", "Export Opportunity"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("seller", models.CharField(max_length=255)),
                ("seller_email", models.EmailField(max_length=254)),
                ("seller_phone", models.CharField(blank=True, max_length=20)),
                ("images", models.JSONField(default=list)),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "marketplace_resources",
            },
        ),
        migrations.CreateModel(
            name="TradeRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.TextField()),
                (
                    "proposed_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="marketplace.marketplaceresource",
                    ),
                ),
            ],
            options={
                "db_table": "trade_requests",
            },
        ),
        migrations.AddIndex(
            model_name="marketplaceresource",
            index=models.Index(
                fields=["resource_type", "is_available"],
                name="marketplace_resourc_50e88e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceresource",
            index=models.Index(
                fields=["country"], name="marketplace_country_4c517f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="marketplaceresource",
            index=models.Index(
                fields=["created_at"], name="marketplace_created_c2243e_idx"
            ),
        ),
    ]
