# Generated by Django 4.2.7 on 2026-08-26 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="marketplaceresource",
            name="published_at",
        ),
    ]
